### ISSUE TITLE
Suggestion: Display name changes should be a new message

### ISSUE THREAD

**Issue by misslivirose** [MozillaReality/hubs-discord-bot#18]
Currently, if you are in a linked room and change your display name, instead of it showing up as: '<old display name> is now known as <new display name>', the bot edits the original message when you joined to reflect your new display name. This could make it harder to track down who is in the room. If the users can change their display names (even with the authentication to their Discord identity) then I think it makes more sense to have it as a message that mirrors what is said in the room chat.

**Comment by mqp** [comment]
The biggest reason I did it this way (editing the existing message) is because the first time you join the lobby, you get an autogenerated display name that you didn't choose or endorse, and it feels a little ridiculous to have the log full of "Whistler-Cake-14849 joined. Whistler-Cake-14849 is now known as Alice." But I agree that mirroring the room chat is a good property, and full traceability of what's going on is also good, so if you feel strongly then I will change it.

**Comment by mqp** [comment]
(By the way, I don't know if you noticed this, but it only edits the original message if you do it right after you join. If you change your display name later, it adds a new message.)

**Comment by misslivirose** [comment]
That makes sense - I changed it within a minute or two of joining, so I can imagine that I did that quickly enough to have it change the original message. That said, I think it could be confusing to still see someone join and not have a record of them later, but maybe just shortening the time frame between editing and making a new message would suffice. I'm seeing it still updating the original message 10+ minutes after joining, I would expect it to have a significantly shorter time frame for editing (Maybe around 5 minutes, tops)

**Comment by mqp** [comment]
Ah, it's my mistake -- it doesn't have a time window as long as the last arrival was of the same person.

I think I will add a short time window. Actually, I would shoot for even shorter than 5 minutes -- more like 1 minute, since I'm really only trying to deal with the "joined the lobby, instantly changed name before joining room" case. If you still see instances where this behavior seemed confusing or concerning let me know.

**Comment by misslivirose** [comment]
That sounds great 👍
