### ISSUE TITLE
Asks to pick a scene when return later

### ISSUE THREAD

**Issue by blairmacintyre** [MozillaReality/hubs-discord-bot#26]
I set up a room connected to my discord channel, went in and pins a media element (twitch stream).  Left.  

When I returned the next day, I went to the room and it looked as I left it (same scene, video pinned in the same place and playing while I was still in the lobby, as expected), BUT it dropped me in the part of the UI flow where it asks me if I want to pick a scene.  If I change the scene all the media stays as it was but the room changes out from under it.

Is this only shown to me because I created the room?  This seems broken and not what I'd expect.   Generally media in a space are likely placed relative to the space;  allowing the space to be changed during entry seems broken to me.

I'd expect (when I return to a room) to be at that part of the flow, but not be able to change the scene, and if I wanted to change the scene being used by a room that I would either destroy the room and start over, or use some in-world editing available to the owner.

(Especially because originally, I'd picked one of the standard scenes (the room with the fan and mozilla on the wall) but that's not an option in this "pick a scene" dialog, so I could never switch back to it ... but, that's not really the point).

**Comment by gfodor** [comment]
hmm, I think what you're seeing is by design. the room owner always has the ability to change the scene. the media carrying over is definitely not ideal, we have some longer term ideas around how to address that but it will always be difficult to deal with if there is media and the owner wants to change the scene. the second CTA in the lobby is only visible to those who have permissions. being able to change the scene at any time is something we added for a number of reasons, one of which is that rooms created from discord will be created in a single action (with no option to select a scene.) we're also going to be dropping the scene selector from the homepage once we have the scene library tuned up. (the carousel scenes are not migrated yet.)

**Comment by blairmacintyre** [comment]
ok, sounds reasonable.  It was surprising so I wanted to check.
